"""Tambahkan kolom Google login

Revision ID: aaa59c10d30d
Revises: 
Create Date: 2025-08-18 22:54:41.811004

"""
import geoalchemy2
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aaa59c10d30d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('data_lahan', schema=None) as batch_op:
        batch_op.alter_column('id_pemilik',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('titik_ordinat',
               existing_type=geoalchemy2.types.Geometry(geometry_type='POLYGON', srid=4326, spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry', _spatial_index_reflected=True),
               type_=sa.Text(),
               existing_nullable=True)
        batch_op.alter_column('bukti_luas_sertifikat',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=True)

    with op.batch_alter_table('hama_penyakit', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_id_lahan'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'data_lahan', ['id_lahan'], ['id_lahan'])

    with op.batch_alter_table('monitoring_tanaman', schema=None) as batch_op:
        batch_op.alter_column('id_lahan',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('pemeliharaan_tanaman', schema=None) as batch_op:
        batch_op.alter_column('id_lahan',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('petani', schema=None) as batch_op:
        batch_op.add_column(sa.Column('google_id', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('google_email', sa.String(length=100), nullable=True))
        batch_op.alter_column('nik',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=16),
               nullable=False)
        batch_op.create_index('idx_petani_titik_rumah', ['titik_rumah'], unique=False, postgresql_using='gist')
        batch_op.create_unique_constraint(None, ['nik'])
        batch_op.create_unique_constraint(None, ['google_id'])
        batch_op.create_unique_constraint(None, ['google_email'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('petani', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_index('idx_petani_titik_rumah', postgresql_using='gist')
        batch_op.alter_column('nik',
               existing_type=sa.String(length=16),
               type_=sa.VARCHAR(length=20),
               nullable=True)
        batch_op.drop_column('google_email')
        batch_op.drop_column('google_id')

    with op.batch_alter_table('pemeliharaan_tanaman', schema=None) as batch_op:
        batch_op.alter_column('id_lahan',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('monitoring_tanaman', schema=None) as batch_op:
        batch_op.alter_column('id_lahan',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('hama_penyakit', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_id_lahan'), 'data_lahan', ['id_lahan'], ['id_lahan'], ondelete='CASCADE')

    with op.batch_alter_table('data_lahan', schema=None) as batch_op:
        batch_op.alter_column('bukti_luas_sertifikat',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('titik_ordinat',
               existing_type=sa.Text(),
               type_=geoalchemy2.types.Geometry(geometry_type='POLYGON', srid=4326, spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry', _spatial_index_reflected=True),
               existing_nullable=True)
        batch_op.alter_column('id_pemilik',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
